"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { X, ArrowLeft, Loader2 } from "lucide-react";
import { buildSrcdoc } from "@/lib/ui-contract";
import type { ProviderId } from "@/types/os";

// The AI browser: FRAMEWORK chrome (address bar, back) around a sandboxed iframe
// whose page is generated by the model for the entered address/query. In-page
// links/searches call caleidos.requestChange(newAddress) (CALEIDOS_CHANGE),
// which navigates the browser to a freshly generated page. No real web, so no
// X-Frame-Options issues; infinite and consistent with the hallucinated OS.
// Page generation goes through the provider abstraction, so the local model works.
export function Browser({
  provider,
  onClose,
}: {
  provider: ProviderId;
  onClose: () => void;
}) {
  const iframeRef = useRef<HTMLIFrameElement>(null);
  const [address, setAddress] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [history, setHistory] = useState<string[]>([]);

  const navigate = useCallback(
    async (query: string) => {
      const q = query.trim();
      if (!q || loading) return;
      setLoading(true);
      setError(null);
      setAddress(q);
      try {
        const resp = await fetch("/api/render", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ target: "page", request: q, provider }),
        });
        if (!resp.ok || !resp.body) {
          setError(`page load failed (${resp.status})`);
          return;
        }
        const reader = resp.body.getReader();
        const decoder = new TextDecoder();
        let html = "";
        for (;;) {
          const { done, value } = await reader.read();
          if (done) break;
          html += decoder.decode(value, { stream: true });
        }
        if (html.includes("CALEIDOS_ERROR")) {
          setError(html.replace(/[\s\S]*CALEIDOS_ERROR:/, "").replace(/-->[\s\S]*/, "").trim());
          return;
        }
        if (iframeRef.current) iframeRef.current.srcdoc = buildSrcdoc(html, null);
        setHistory((prev) => [...prev, q]);
      } catch (e) {
        setError(e instanceof Error ? e.message : String(e));
      } finally {
        setLoading(false);
      }
    },
    [loading, provider],
  );

  // In-page navigation: the page calls caleidos.requestChange(newAddress).
  useEffect(() => {
    function onMessage(e: MessageEvent) {
      if (e.source !== iframeRef.current?.contentWindow) return;
      const d = e.data as { type?: string; request?: string };
      if (d?.type === "CALEIDOS_CHANGE" && d.request) navigate(d.request);
    }
    window.addEventListener("message", onMessage);
    return () => window.removeEventListener("message", onMessage);
  }, [navigate]);

  const back = useCallback(() => {
    setHistory((prev) => {
      if (prev.length < 2) return prev;
      const target = prev[prev.length - 2];
      const next = prev.slice(0, -1);
      // navigate without re-pushing (so we pop one)
      navigate(target);
      return next.slice(0, -1);
    });
  }, [navigate]);

  return (
    <div className="fixed inset-0 z-[10000] flex items-center justify-center bg-black/40 backdrop-blur-sm" onClick={onClose}>
      <div
        className="flex h-[80vh] w-[min(1000px,94vw)] flex-col overflow-hidden rounded-2xl border border-black/10 bg-white shadow-2xl"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center gap-2 border-b border-black/10 bg-neutral-100 px-3 py-2">
          <button
            onClick={back}
            disabled={history.length < 2}
            aria-label="back"
            className="text-neutral-500 disabled:opacity-30"
          >
            <ArrowLeft className="h-4 w-4" />
          </button>
          <div className="flex flex-1 items-center gap-2 rounded-lg border border-neutral-200 bg-white px-3 py-1.5">
            {loading ? (
              <Loader2 className="h-3.5 w-3.5 animate-spin text-neutral-400" />
            ) : (
              <span className="h-2 w-2 rounded-full bg-emerald-400" />
            )}
            <input
              autoFocus
              value={address}
              onChange={(e) => setAddress(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === "Enter") {
                  e.preventDefault();
                  navigate(address);
                }
              }}
              placeholder="enter an address or search the web of another dimension..."
              className="flex-1 bg-transparent text-sm text-neutral-800 placeholder:text-neutral-400 focus:outline-none"
            />
          </div>
          <button onClick={onClose} aria-label="close" className="text-neutral-400 hover:text-neutral-700">
            <X className="h-4 w-4" />
          </button>
        </div>

        <div className="relative flex-1 bg-white">
          <iframe
            ref={iframeRef}
            sandbox="allow-scripts"
            className="h-full w-full border-0"
            title="browser page"
          />
          {history.length === 0 && !loading && !error && (
            <div className="pointer-events-none absolute inset-0 flex items-center justify-center">
              <p className="text-center text-sm text-neutral-400">
                type anything above. every page is generated on the spot.
              </p>
            </div>
          )}
          {error && (
            <div className="absolute inset-x-0 top-0 bg-red-50 p-3 text-center text-xs text-red-600">{error}</div>
          )}
        </div>
      </div>
    </div>
  );
}
